"""
ml/recommender.py

Improved strict per-user personalized recommendation engine.

Production recommendations depend ONLY on the currently logged-in
user's own interaction history.

Allowed user signals:
    - views
    - likes
    - saves

Article representation:
    - TF-IDF article text
    - title + description TF-IDF
    - category
    - recency

Recommendation pipeline:

    User interactions
        ↓
    User preference profile
        ↓
    Candidate generation
        ↓
    Content similarity
        ↓
    Category preference
        ↓
    Recency
        ↓
    Personalized scoring
        ↓
    Diversity re-ranking
        ↓
    Top N recommendations

NOT used for production recommendations:
    - other users' interactions
    - global popularity
    - collaborative filtering
    - NCF predictions
    - shared user profiles

IMPORTANT:

The production feature catalogue is generated by:

    ml.feature_extraction

and is aligned to the live Article database using:

    Article.id ASC

The offline evaluation helper additionally verifies that a saved
feature row actually represents the current database Article by URL
or title before using the saved production feature catalogue.

This prevents numeric Article-ID collisions in isolated pytest
databases.
"""

import json
import math
import os
import sys

import joblib
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from sqlalchemy import func

from app import create_app, db
from app.models import Article, Interaction


# =====================================================================
# PATHS
# =====================================================================

DATA_DIR = os.path.join(
    "data",
    "processed",
)


# ---------------------------------------------------------------------
# Improved feature artifacts
# ---------------------------------------------------------------------

TEXT_VECTORIZER_PATH = os.path.join(
    DATA_DIR,
    "tfidf_vectorizer.joblib",
)

TEXT_MATRIX_PATH = os.path.join(
    DATA_DIR,
    "tfidf_matrix.joblib",
)

TITLE_VECTORIZER_PATH = os.path.join(
    DATA_DIR,
    "title_tfidf_vectorizer.joblib",
)

TITLE_MATRIX_PATH = os.path.join(
    DATA_DIR,
    "title_tfidf_matrix.joblib",
)

CATEGORY_ENCODER_PATH = os.path.join(
    DATA_DIR,
    "category_encoder.joblib",
)

CATEGORY_MATRIX_PATH = os.path.join(
    DATA_DIR,
    "category_matrix.joblib",
)

RECENCY_MATRIX_PATH = os.path.join(
    DATA_DIR,
    "recency_matrix.joblib",
)

FEATURE_MATRIX_PATH = os.path.join(
    DATA_DIR,
    "article_feature_matrix.joblib",
)

ARTICLES_INDEX_PATH = os.path.join(
    DATA_DIR,
    "articles_index.json",
)

FEATURE_METADATA_PATH = os.path.join(
    DATA_DIR,
    "article_feature_metadata.json",
)


# ---------------------------------------------------------------------
# Old artifacts retained for compatibility.
# ---------------------------------------------------------------------

OLD_VECTORIZER_PATH = os.path.join(
    DATA_DIR,
    "db_tfidf_vectorizer.joblib",
)

OLD_MATRIX_PATH = os.path.join(
    DATA_DIR,
    "db_tfidf_matrix.joblib",
)

OLD_ARTICLE_ID_MAP_PATH = os.path.join(
    DATA_DIR,
    "article_id_map.json",
)


# =====================================================================
# RECOMMENDER CONFIGURATION
# =====================================================================

# Stronger user actions receive stronger preference weights.
#
# These are applied ONLY to the current user's interactions.

INTERACTION_WEIGHTS = {
    "view": 1.0,
    "like": 2.0,
    "save": 3.0,
}


# Compatibility constant retained for older tests/code.
#
# It is NOT used as a popularity fallback in production.

COLD_START_THRESHOLD = 3


# ---------------------------------------------------------------------
# Feature weights
# ---------------------------------------------------------------------

# Article text is the strongest signal.

CONTENT_WEIGHT = 0.55


# Category preference is built ONLY from this user's own history.

CATEGORY_WEIGHT = 0.20


# Fresher articles receive a freshness signal.

RECENCY_WEIGHT = 0.15


# Title/description receives its own contribution.

TITLE_WEIGHT = 0.10


# ---------------------------------------------------------------------
# Candidate configuration
# ---------------------------------------------------------------------

DEFAULT_CANDIDATE_POOL = 100


# ---------------------------------------------------------------------
# Diversity configuration
# ---------------------------------------------------------------------

DIVERSITY_LAMBDA = 0.20

MAX_SAME_CATEGORY_IN_TOP_FEED = 3


# =====================================================================
# GENERAL HELPERS
# =====================================================================

def safe_text(value):
    """
    Return a normalized string representation.
    """

    if value is None:
        return ""

    return str(value).strip()


def normalize_scores(values):
    """
    Min-max normalize numeric values into approximately [0, 1].

    If all values are identical, return 0.5 for every value so that
    the feature does not completely disappear.
    """

    values = np.asarray(
        values,
        dtype=float,
    )

    if values.size == 0:
        return values

    minimum = np.min(
        values
    )

    maximum = np.max(
        values
    )

    if math.isclose(
        float(maximum),
        float(minimum),
    ):
        return np.full(
            values.shape,
            0.5,
            dtype=float,
        )

    return (
        values - minimum
    ) / (
        maximum - minimum
    )


# =====================================================================
# LOAD IMPROVED CONTENT ARTIFACTS
# =====================================================================

def load_content_artifacts():
    """
    Load the improved article feature artifacts.

    Returns
    -------
    dict
        Contains all feature matrices and article metadata.
    """

    required_paths = [
        TEXT_VECTORIZER_PATH,
        TEXT_MATRIX_PATH,
        TITLE_VECTORIZER_PATH,
        TITLE_MATRIX_PATH,
        CATEGORY_ENCODER_PATH,
        CATEGORY_MATRIX_PATH,
        RECENCY_MATRIX_PATH,
        FEATURE_MATRIX_PATH,
        ARTICLES_INDEX_PATH,
    ]

    for path in required_paths:

        if not os.path.exists(
            path
        ):
            raise FileNotFoundError(
                f"Required recommender artifact not found: "
                f"{path}\n"
                "Run:\n"
                "    python -m ml.feature_extraction\n"
                "before using the improved recommender."
            )

    text_vectorizer = joblib.load(
        TEXT_VECTORIZER_PATH
    )

    text_matrix = joblib.load(
        TEXT_MATRIX_PATH
    )

    title_vectorizer = joblib.load(
        TITLE_VECTORIZER_PATH
    )

    title_matrix = joblib.load(
        TITLE_MATRIX_PATH
    )

    category_encoder = joblib.load(
        CATEGORY_ENCODER_PATH
    )

    category_matrix = joblib.load(
        CATEGORY_MATRIX_PATH
    )

    recency_matrix = joblib.load(
        RECENCY_MATRIX_PATH
    )

    feature_matrix = joblib.load(
        FEATURE_MATRIX_PATH
    )

    with open(
        ARTICLES_INDEX_PATH,
        "r",
        encoding="utf-8",
    ) as f:

        article_index = json.load(
            f
        )

    metadata = {}

    if os.path.exists(
        FEATURE_METADATA_PATH
    ):

        with open(
            FEATURE_METADATA_PATH,
            "r",
            encoding="utf-8",
        ) as f:

            metadata = json.load(
                f
            )

    # ---------------------------------------------------------------
    # Basic shape validation.
    # ---------------------------------------------------------------

    matrix_row_counts = [
        text_matrix.shape[0],
        title_matrix.shape[0],
        category_matrix.shape[0],
        recency_matrix.shape[0],
        feature_matrix.shape[0],
        len(article_index),
    ]

    if len(
        set(matrix_row_counts)
    ) != 1:

        raise RuntimeError(
            "Recommender feature artifacts are not aligned.\n"
            f"Row counts found: {matrix_row_counts}\n\n"
            "Run:\n"
            "    python -m ml.feature_extraction"
            "\n"
            "to rebuild the feature catalogue."
        )

    return {
        "text_vectorizer": (
            text_vectorizer
        ),
        "text_matrix": (
            text_matrix
        ),
        "title_vectorizer": (
            title_vectorizer
        ),
        "title_matrix": (
            title_matrix
        ),
        "category_encoder": (
            category_encoder
        ),
        "category_matrix": (
            category_matrix
        ),
        "recency_matrix": (
            recency_matrix
        ),
        "feature_matrix": (
            feature_matrix
        ),
        "article_index": (
            article_index
        ),
        "metadata": metadata,
    }


# =====================================================================
# ARTICLE ID → FEATURE ROW MAPPING
# =====================================================================

def build_article_row_mapping(
    article_index,
):
    """
    Build a mapping between database Article IDs and feature rows.

    The current feature extractor stores the REAL database Article.id
    explicitly in articles_index.json.

    Therefore the normal production mapping is:

        Article.id -> feature row

    URL/title matching is retained as a compatibility mechanism for
    older indexes that might not contain explicit IDs.
    """

    row_by_article_id = {}

    # -----------------------------------------------------------------
    # First: use explicit Article IDs.
    # -----------------------------------------------------------------

    for row_number, item in enumerate(
        article_index
    ):

        possible_ids = [
            item.get("id"),
            item.get("article_id"),
        ]

        for value in possible_ids:

            if value is None:
                continue

            try:
                article_id = int(
                    value
                )

            except (
                TypeError,
                ValueError,
            ):
                continue

            row_by_article_id[
                article_id
            ] = row_number

    # -----------------------------------------------------------------
    # URL/title lookup tables.
    # -----------------------------------------------------------------

    rows_by_url = {}

    rows_by_title = {}

    for row_number, item in enumerate(
        article_index
    ):

        url = safe_text(
            item.get(
                "url"
            )
        )

        title = safe_text(
            item.get(
                "title"
            )
        )

        if url:

            rows_by_url[
                url
            ] = row_number

        if title:

            rows_by_title[
                title.lower()
            ] = row_number

    # -----------------------------------------------------------------
    # Compatibility matching against the current database.
    #
    # IMPORTANT:
    # Explicit IDs are trusted during normal production use because
    # feature_extraction.py now builds the index directly from the
    # database.
    #
    # URL/title matching is only needed for legacy indexes without IDs.
    # -----------------------------------------------------------------

    database_articles = (
        Article.query.all()
    )

    for article in database_articles:

        article_id = article.id

        if article_id in row_by_article_id:
            continue

        url = safe_text(
            getattr(
                article,
                "url",
                None,
            )
        )

        title = safe_text(
            getattr(
                article,
                "title",
                None,
            )
        )

        row_number = None

        if url:

            row_number = rows_by_url.get(
                url
            )

        if (
            row_number is None
            and title
        ):

            row_number = rows_by_title.get(
                title.lower()
            )

        if row_number is not None:

            row_by_article_id[
                article_id
            ] = row_number

    return row_by_article_id


# =====================================================================
# VERIFY SAVED FEATURE ROW AGAINST DATABASE ARTICLE
# =====================================================================

def artifact_row_matches_database_article(
    article_id,
    row_number,
    article_index,
):
    """
    Verify that a saved feature row actually represents the SAME
    database Article.

    This check is especially important for isolated pytest databases.

    Example problem:

        production Article.id = 1
        test Article.id       = 1

    The numeric ID is identical, but the articles are different.

    Therefore ID alone is not enough for the offline helper.

    Identity checks:

        1. URL, when available
        2. otherwise title

    Returns
    -------
    bool
        True when the saved row matches the current database Article.
    """

    if row_number is None:
        return False

    if (
        row_number < 0
        or row_number >= len(article_index)
    ):
        return False

    database_article = db.session.get(
        Article,
        article_id,
    )

    if database_article is None:
        return False

    indexed_article = article_index[
        row_number
    ]

    database_url = safe_text(
        getattr(
            database_article,
            "url",
            None,
        )
    )

    indexed_url = safe_text(
        indexed_article.get(
            "url"
        )
    )

    # ---------------------------------------------------------------
    # URL is the strongest available identity check.
    # ---------------------------------------------------------------

    if database_url or indexed_url:

        return (
            database_url
            == indexed_url
        )

    # ---------------------------------------------------------------
    # When URL is unavailable, compare titles.
    # ---------------------------------------------------------------

    database_title = safe_text(
        getattr(
            database_article,
            "title",
            None,
        )
    ).lower()

    indexed_title = safe_text(
        indexed_article.get(
            "title"
        )
    ).lower()

    return (
        database_title
        == indexed_title
    )


# =====================================================================
# USER INTERACTIONS
# =====================================================================

def get_user_interactions(
    user_id,
):
    """
    Return ONLY interactions belonging to user_id.

    No other user's interaction history is queried.
    """

    rows = (
        Interaction.query
        .filter_by(
            user_id=user_id
        )
        .order_by(
            Interaction.timestamp.asc(),
            Interaction.id.asc(),
        )
        .all()
    )

    return [
        (
            row.article_id,
            row.type,
        )
        for row in rows
    ]


# =====================================================================
# USER CATEGORY PREFERENCES
# =====================================================================

def build_user_category_preferences(
    user_id,
):
    """
    Build category preference scores from ONLY this user's history.

    Interaction weights:

        view -> 1
        like -> 2
        save -> 3
    """

    interactions = (
        get_user_interactions(
            user_id
        )
    )

    if not interactions:
        return {}

    category_scores = {}

    for (
        article_id,
        interaction_type,
    ) in interactions:

        article = db.session.get(
            Article,
            article_id,
        )

        if article is None:
            continue

        category = (
            safe_text(
                getattr(
                    article,
                    "category",
                    None,
                )
            ).lower()
            or "unknown"
        )

        weight = INTERACTION_WEIGHTS.get(
            interaction_type,
            1.0,
        )

        category_scores[
            category
        ] = (
            category_scores.get(
                category,
                0.0,
            )
            + weight
        )

    if not category_scores:
        return {}

    total = sum(
        category_scores.values()
    )

    if total <= 0:
        return {}

    return {
        category: score / total
        for (
            category,
            score,
        ) in category_scores.items()
    }


# =====================================================================
# BUILD USER CONTENT PROFILE
# =====================================================================

def build_user_profile_vector(
    user_id,
    text_matrix,
    title_matrix,
    article_id_to_row,
):
    """
    Build a personalized content profile from ONLY this user's
    interactions.

    Returns:

        (
            text_profile,
            title_profile,
            interacted_article_ids
        )
    """

    interactions = (
        get_user_interactions(
            user_id
        )
    )

    if not interactions:

        return (
            None,
            None,
            set(),
        )

    text_vectors = []

    title_vectors = []

    weights = []

    interacted_ids = set()

    for (
        article_id,
        interaction_type,
    ) in interactions:

        interacted_ids.add(
            article_id
        )

        row_number = (
            article_id_to_row.get(
                article_id
            )
        )

        if row_number is None:
            continue

        weight = INTERACTION_WEIGHTS.get(
            interaction_type,
            1.0,
        )

        text_vectors.append(
            text_matrix[
                row_number
            ].toarray()[0]
        )

        title_vectors.append(
            title_matrix[
                row_number
            ].toarray()[0]
        )

        weights.append(
            weight
        )

    if not text_vectors:

        return (
            None,
            None,
            interacted_ids,
        )

    text_vectors = np.asarray(
        text_vectors,
        dtype=float,
    )

    title_vectors = np.asarray(
        title_vectors,
        dtype=float,
    )

    weights = np.asarray(
        weights,
        dtype=float,
    ).reshape(
        -1,
        1,
    )

    total_weight = (
        weights.sum()
    )

    if total_weight <= 0:

        return (
            None,
            None,
            interacted_ids,
        )

    text_profile = (
        text_vectors
        * weights
    ).sum(
        axis=0
    ) / total_weight

    title_profile = (
        title_vectors
        * weights
    ).sum(
        axis=0
    ) / total_weight

    return (
        text_profile,
        title_profile,
        interacted_ids,
    )


# =====================================================================
# RECENCY
# =====================================================================

def get_recency_score_from_matrix(
    recency_matrix,
    row_number,
):
    """
    Return the precomputed article recency score.
    """

    value = (
        recency_matrix[
            row_number
        ].toarray()[0][0]
    )

    return float(
        max(
            0.0,
            min(
                1.0,
                value,
            ),
        )
    )


# =====================================================================
# CATEGORY LOOKUP
# =====================================================================

def build_category_by_row(
    article_index,
):
    """
    Return:

        row_number -> normalized category
    """

    result = {}

    for row_number, item in enumerate(
        article_index
    ):

        category = (
            safe_text(
                item.get(
                    "category"
                )
            ).lower()
            or "unknown"
        )

        result[
            row_number
        ] = category

    return result


# =====================================================================
# CANDIDATE GENERATION
# =====================================================================

def generate_candidates(
    text_similarities,
    title_similarities,
    interacted_ids,
    article_ids,
    article_id_to_row,
    candidate_pool_size,
):
    """
    Generate a candidate pool using content similarity.

    Already-interacted articles are excluded.
    """

    combined_similarity = (
        0.65 * text_similarities
        + 0.35 * title_similarities
    )

    candidate_rows = []

    sorted_rows = np.argsort(
        combined_similarity
    )[::-1]

    for row_number in sorted_rows:

        article_id = article_ids[
            row_number
        ]

        if article_id in interacted_ids:
            continue

        candidate_rows.append(
            (
                row_number,
                article_id,
                float(
                    combined_similarity[
                        row_number
                    ]
                ),
            )
        )

        if (
            len(candidate_rows)
            >= candidate_pool_size
        ):
            break

    return candidate_rows


# =====================================================================
# PERSONALIZED SCORING
# =====================================================================

def calculate_personalized_scores(
    candidates,
    text_similarities,
    title_similarities,
    category_preferences,
    category_by_row,
    recency_matrix,
):
    """
    Calculate final personalized scores.

    Components:

        55% article text similarity
        10% title/description similarity
        20% user's category preference
        15% article recency
    """

    if not candidates:
        return []

    text_values = [
        text_similarities[
            row_number
        ]
        for (
            row_number,
            _article_id,
            _candidate_score,
        ) in candidates
    ]

    title_values = [
        title_similarities[
            row_number
        ]
        for (
            row_number,
            _article_id,
            _candidate_score,
        ) in candidates
    ]

    recency_values = [
        get_recency_score_from_matrix(
            recency_matrix,
            row_number,
        )
        for (
            row_number,
            _article_id,
            _candidate_score,
        ) in candidates
    ]

    text_values = normalize_scores(
        text_values
    )

    title_values = normalize_scores(
        title_values
    )

    recency_values = normalize_scores(
        recency_values
    )

    scored = []

    for index, (
        row_number,
        article_id,
        _candidate_score,
    ) in enumerate(
        candidates
    ):

        text_content_score = float(
            text_values[
                index
            ]
        )

        title_content_score = float(
            title_values[
                index
            ]
        )

        category = category_by_row.get(
            row_number,
            "unknown",
        )

        category_score = (
            category_preferences.get(
                category,
                0.0,
            )
        )

        # -----------------------------------------------------------
        # Normalize category preference relative to the user's
        # strongest category.
        # -----------------------------------------------------------

        if category_preferences:

            maximum_category = max(
                category_preferences.values()
            )

            if maximum_category > 0:

                category_score = (
                    category_score
                    / maximum_category
                )

        recency_score = float(
            recency_values[
                index
            ]
        )

        # -----------------------------------------------------------
        # Final personalized score.
        # -----------------------------------------------------------

        final_score = (
            CONTENT_WEIGHT
            * text_content_score

            + TITLE_WEIGHT
            * title_content_score

            + CATEGORY_WEIGHT
            * category_score

            + RECENCY_WEIGHT
            * recency_score
        )

        content_score = (
            0.70
            * text_content_score
            + 0.30
            * title_content_score
        )

        scored.append(
            {
                "row": row_number,
                "article_id": article_id,
                "content_score": float(
                    content_score
                ),
                "category_score": float(
                    category_score
                ),
                "recency_score": float(
                    recency_score
                ),
                "score": float(
                    final_score
                ),
            }
        )

    scored.sort(
        key=lambda item: item[
            "score"
        ],
        reverse=True,
    )

    return scored


# =====================================================================
# DIVERSITY RE-RANKING
# =====================================================================

def diversity_rerank(
    scored_candidates,
    feature_matrix,
    category_by_row,
    top_n,
):
    """
    Re-rank candidates to balance relevance and diversity.

    Uses a simplified MMR-style approach.

    The combined article feature matrix includes:

        text
        title
        category
        recency
    """

    if not scored_candidates:
        return []

    if top_n <= 0:
        return []

    remaining = list(
        scored_candidates
    )

    selected = []

    selected_rows = []

    category_counts = {}

    while (
        remaining
        and len(selected) < top_n
    ):

        best_candidate = None

        best_mmr_score = None

        best_index = None

        for index, candidate in enumerate(
            remaining
        ):

            row_number = candidate[
                "row"
            ]

            relevance = candidate[
                "score"
            ]

            category = category_by_row.get(
                row_number,
                "unknown",
            )

            category_count = (
                category_counts.get(
                    category,
                    0,
                )
            )

            # -------------------------------------------------------
            # Category repetition penalty.
            # -------------------------------------------------------

            category_penalty = 0.0

            if (
                category_count
                >= MAX_SAME_CATEGORY_IN_TOP_FEED
            ):
                category_penalty = 0.15

            # -------------------------------------------------------
            # Similarity to already selected articles.
            # -------------------------------------------------------

            max_similarity = 0.0

            if selected_rows:

                candidate_vector = (
                    feature_matrix[
                        row_number
                    ]
                )

                selected_matrix = (
                    feature_matrix[
                        selected_rows
                    ]
                )

                similarities = (
                    cosine_similarity(
                        candidate_vector,
                        selected_matrix,
                    ).flatten()
                )

                if similarities.size:

                    max_similarity = float(
                        np.max(
                            similarities
                        )
                    )

            # -------------------------------------------------------
            # MMR score.
            # -------------------------------------------------------

            mmr_score = (
                (1.0 - DIVERSITY_LAMBDA)
                * relevance

                - DIVERSITY_LAMBDA
                * max_similarity

                - category_penalty
            )

            if (
                best_mmr_score is None
                or mmr_score
                > best_mmr_score
            ):

                best_mmr_score = (
                    mmr_score
                )

                best_candidate = (
                    candidate
                )

                best_index = index

        if best_candidate is None:
            break

        selected.append(
            best_candidate
        )

        selected_rows.append(
            best_candidate[
                "row"
            ]
        )

        category = (
            category_by_row.get(
                best_candidate[
                    "row"
                ],
                "unknown",
            )
        )

        category_counts[
            category
        ] = (
            category_counts.get(
                category,
                0,
            )
            + 1
        )

        remaining.pop(
            best_index
        )

    return selected


# =====================================================================
# MAIN PERSONALIZED RECOMMENDER
# =====================================================================

def personalized_recommend(
    user_id,
    top_n=20,
    candidate_pool_size=None,
):
    """
    Generate strictly personalized recommendations.

    IMPORTANT:

        Recommendations depend ONLY on the current user's own
        interactions.

    They do NOT use:

        - another user's interactions
        - global popularity
        - NCF
        - collaborative filtering

    Steps:

        1. Load article features.
        2. Build Article ID -> feature-row mapping.
        3. Read only current user's interactions.
        4. Build the user's weighted content profile.
        5. Build the user's category preferences.
        6. Calculate article similarities.
        7. Generate candidates.
        8. Calculate personalized scores.
        9. Apply diversity re-ranking.
        10. Return Top N.
    """

    if top_n <= 0:
        return []

    if candidate_pool_size is None:

        candidate_pool_size = max(
            DEFAULT_CANDIDATE_POOL,
            top_n * 5,
        )

    # -----------------------------------------------------------------
    # STEP 1
    # Load article feature artifacts.
    # -----------------------------------------------------------------

    artifacts = (
        load_content_artifacts()
    )

    text_matrix = artifacts[
        "text_matrix"
    ]

    title_matrix = artifacts[
        "title_matrix"
    ]

    recency_matrix = artifacts[
        "recency_matrix"
    ]

    feature_matrix = artifacts[
        "feature_matrix"
    ]

    article_index = artifacts[
        "article_index"
    ]

    # -----------------------------------------------------------------
    # STEP 2
    # Build Article ID -> feature-row mapping.
    # -----------------------------------------------------------------

    article_id_to_row = (
        build_article_row_mapping(
            article_index
        )
    )

    # -----------------------------------------------------------------
    # Build row -> Article ID mapping.
    # -----------------------------------------------------------------

    article_ids = [
        None
        for _ in article_index
    ]

    for (
        article_id,
        row_number,
    ) in article_id_to_row.items():

        if (
            0 <= row_number
            < len(article_ids)
        ):

            article_ids[
                row_number
            ] = article_id

    # -----------------------------------------------------------------
    # Validate mapping.
    # -----------------------------------------------------------------

    if not all(
        article_id is not None
        for article_id in article_ids
    ):

        missing_rows = [
            row_number
            for row_number, article_id
            in enumerate(article_ids)
            if article_id is None
        ]

        raise RuntimeError(
            "Some feature rows could not be mapped to database "
            "Article IDs.\n"
            f"Missing feature rows: "
            f"{missing_rows[:20]}\n"
            f"Total missing rows: "
            f"{len(missing_rows)}\n\n"
            "Run:\n"
            "    python -m ml.feature_extraction\n"
            "to rebuild the database-aligned feature catalogue."
        )

    # -----------------------------------------------------------------
    # STEP 3
    # Get ONLY this user's interactions.
    # -----------------------------------------------------------------

    interactions = (
        get_user_interactions(
            user_id
        )
    )

    # Strict cold-start behavior.
    #
    # No popularity fallback.
    # No other user's profile.

    if not interactions:
        return []

    # -----------------------------------------------------------------
    # STEP 4
    # Build current user's content profile.
    # -----------------------------------------------------------------

    (
        text_profile,
        title_profile,
        interacted_ids,
    ) = build_user_profile_vector(
        user_id=user_id,
        text_matrix=text_matrix,
        title_matrix=title_matrix,
        article_id_to_row=article_id_to_row,
    )

    if (
        text_profile is None
        or title_profile is None
    ):
        return []

    # -----------------------------------------------------------------
    # STEP 5
    # Build current user's category preferences.
    # -----------------------------------------------------------------

    category_preferences = (
        build_user_category_preferences(
            user_id
        )
    )

    category_by_row = (
        build_category_by_row(
            article_index
        )
    )

    # -----------------------------------------------------------------
    # STEP 6
    # Calculate similarity to user's profile.
    # -----------------------------------------------------------------

    text_profile = (
        text_profile.reshape(
            1,
            -1,
        )
    )

    title_profile = (
        title_profile.reshape(
            1,
            -1,
        )
    )

    text_similarities = (
        cosine_similarity(
            text_profile,
            text_matrix,
        ).flatten()
    )

    title_similarities = (
        cosine_similarity(
            title_profile,
            title_matrix,
        ).flatten()
    )

    # -----------------------------------------------------------------
    # STEP 7
    # Generate candidates.
    # -----------------------------------------------------------------

    candidates = generate_candidates(
        text_similarities=text_similarities,
        title_similarities=title_similarities,
        interacted_ids=interacted_ids,
        article_ids=article_ids,
        article_id_to_row=article_id_to_row,
        candidate_pool_size=candidate_pool_size,
    )

    if not candidates:
        return []

    # -----------------------------------------------------------------
    # STEP 8
    # Personalized scoring.
    # -----------------------------------------------------------------

    scored_candidates = (
        calculate_personalized_scores(
            candidates=candidates,
            text_similarities=text_similarities,
            title_similarities=title_similarities,
            category_preferences=category_preferences,
            category_by_row=category_by_row,
            recency_matrix=recency_matrix,
        )
    )

    if not scored_candidates:
        return []

    # -----------------------------------------------------------------
    # STEP 9
    # Diversity re-ranking.
    # -----------------------------------------------------------------

    reranked = diversity_rerank(
        scored_candidates=scored_candidates,
        feature_matrix=feature_matrix,
        category_by_row=category_by_row,
        top_n=top_n,
    )

    # -----------------------------------------------------------------
    # STEP 10
    # Return article IDs and personalized scores.
    # -----------------------------------------------------------------

    return [
        (
            candidate[
                "article_id"
            ],
            float(
                candidate[
                    "score"
                ]
            ),
        )
        for candidate in reranked
    ]


# =====================================================================
# OFFLINE EVALUATION RECOMMENDER
# =====================================================================

def recommend_from_interactions(
    interactions,
    exclude_ids=None,
    top_n=10,
):
    """
    Generate recommendations from an explicit interaction list.

    This function is used by the offline evaluation system.

    IMPORTANT:

        It uses ONLY the interactions supplied to this function.

        It does NOT query another user's interaction history to build
        the recommendation profile.

    Normal operation uses the production feature catalogue.

    Special isolated-database behavior:

        If the interaction Article IDs collide numerically with IDs
        in the production feature catalogue but the URLs/titles do
        not match, a temporary TF-IDF catalogue is built from the
        CURRENT database.

    That protects pytest and other isolated evaluation environments.
    """

    # -----------------------------------------------------------------
    # Basic argument validation.
    # -----------------------------------------------------------------

    if top_n <= 0:
        return []

    interactions = list(
        interactions
    )

    if not interactions:
        return []

    exclude_ids = set(
        exclude_ids or []
    )

    interaction_article_ids = {
        article_id
        for (
            article_id,
            _interaction_type,
        ) in interactions
    }

    # -----------------------------------------------------------------
    # STEP 1
    # Load production feature artifacts.
    # -----------------------------------------------------------------

    artifacts = (
        load_content_artifacts()
    )

    article_index = artifacts[
        "article_index"
    ]

    article_id_to_row = (
        build_article_row_mapping(
            article_index
        )
    )

    # -----------------------------------------------------------------
    # STEP 2
    # Verify that the saved feature rows really represent the current
    # database articles.
    #
    # IMPORTANT:
    #
    # ID collision example:
    #
    # production Article 1 != pytest Article 1
    #
    # So numeric ID alone is NOT enough here.
    # -----------------------------------------------------------------

    artifact_mapping_usable = True

    for article_id in (
        interaction_article_ids
    ):

        row_number = (
            article_id_to_row.get(
                article_id
            )
        )

        if not artifact_row_matches_database_article(
            article_id=article_id,
            row_number=row_number,
            article_index=article_index,
        ):

            artifact_mapping_usable = False
            break

    # -----------------------------------------------------------------
    # STEP 3
    # Temporary database fallback.
    #
    # This path is primarily for isolated unit-test databases and other
    # situations where the current Article records do not correspond
    # to the saved production feature catalogue.
    #
    # IMPORTANT:
    #
    # This helper uses ONLY the explicit interaction list supplied to
    # the function.
    #
    # It does NOT use another user's interaction history.
    #
    # Production personalized_recommend() does NOT use this fallback.
    # -----------------------------------------------------------------

    if not artifact_mapping_usable:

        articles = (
            Article.query
            .order_by(
                Article.id.asc()
            )
            .all()
        )

        if not articles:
            return []

        article_ids = [
            article.id
            for article in articles
        ]

        # -------------------------------------------------------------
        # Build text corpus from current database records.
        # -------------------------------------------------------------

        def build_fallback_text(
            article,
        ):
            fields = [
                getattr(
                    article,
                    "title",
                    None,
                ),
                getattr(
                    article,
                    "description",
                    None,
                ),
                getattr(
                    article,
                    "content",
                    None,
                ),
                getattr(
                    article,
                    "cleaned_text",
                    None,
                ),
            ]

            parts = [
                safe_text(
                    value
                )
                for value in fields
                if safe_text(
                    value
                )
            ]

            text = " ".join(
                parts
            ).strip()

            if not text:
                text = "article"

            return text

        corpus = [
            build_fallback_text(
                article
            )
            for article in articles
        ]

        if not any(
            text.strip()
            for text in corpus
        ):
            return []

        # -------------------------------------------------------------
        # Build temporary TF-IDF.
        # -------------------------------------------------------------

        vectorizer = (
            TfidfVectorizer(
                max_features=5000,
                min_df=1,
                ngram_range=(1, 2),
                sublinear_tf=True,
            )
        )

        try:

            matrix = (
                vectorizer.fit_transform(
                    corpus
                )
            )

        except ValueError:

            return []

        # -------------------------------------------------------------
        # Temporary Article ID -> row mapping.
        # -------------------------------------------------------------

        fallback_row_by_id = {
            article_id: row_number
            for (
                row_number,
                article_id,
            ) in enumerate(
                article_ids
            )
        }

        # -------------------------------------------------------------
        # Build explicit user's profile.
        # -------------------------------------------------------------

        profile_vectors = []

        profile_weights = []

        for (
            article_id,
            interaction_type,
        ) in interactions:

            row_number = (
                fallback_row_by_id.get(
                    article_id
                )
            )

            if row_number is None:
                continue

            weight = (
                INTERACTION_WEIGHTS.get(
                    interaction_type,
                    1.0,
                )
            )

            profile_vectors.append(
                matrix[
                    row_number
                ].toarray()[0]
            )

            profile_weights.append(
                weight
            )

        if not profile_vectors:
            return []

        profile_vectors = np.asarray(
            profile_vectors,
            dtype=float,
        )

        profile_weights = np.asarray(
            profile_weights,
            dtype=float,
        ).reshape(
            -1,
            1,
        )

        total_weight = (
            profile_weights.sum()
        )

        if total_weight <= 0:
            return []

        profile = (
            profile_vectors
            * profile_weights
        ).sum(
            axis=0
        ) / total_weight

        # -------------------------------------------------------------
        # Calculate similarities.
        # -------------------------------------------------------------

        similarities = (
            cosine_similarity(
                profile.reshape(
                    1,
                    -1,
                ),
                matrix,
            ).flatten()
        )

        # -------------------------------------------------------------
        # Never recommend explicit interaction/excluded articles.
        # -------------------------------------------------------------

        interacted_ids = set(
            exclude_ids
        )

        interacted_ids.update(
            interaction_article_ids
        )

        recommendations = []

        for (
            row_number,
            article_id,
        ) in enumerate(
            article_ids
        ):

            if article_id in interacted_ids:
                continue

            recommendations.append(
                (
                    article_id,
                    float(
                        similarities[
                            row_number
                        ]
                    ),
                )
            )

        recommendations.sort(
            key=lambda item: item[1],
            reverse=True,
        )

        return recommendations[
            :top_n
        ]

    # -----------------------------------------------------------------
    # STEP 4
    # Normal production-artifact path.
    # -----------------------------------------------------------------

    text_matrix = artifacts[
        "text_matrix"
    ]

    title_matrix = artifacts[
        "title_matrix"
    ]

    recency_matrix = artifacts[
        "recency_matrix"
    ]

    feature_matrix = artifacts[
        "feature_matrix"
    ]

    # -----------------------------------------------------------------
    # Build row -> Article ID mapping.
    # -----------------------------------------------------------------

    article_ids = [
        None
        for _ in article_index
    ]

    for (
        article_id,
        row_number,
    ) in article_id_to_row.items():

        if (
            0 <= row_number
            < len(article_ids)
        ):

            article_ids[
                row_number
            ] = article_id

    if not all(
        article_id is not None
        for article_id in article_ids
    ):

        return []

    # -----------------------------------------------------------------
    # STEP 5
    # Build explicit user's profile.
    # -----------------------------------------------------------------

    text_vectors = []

    title_vectors = []

    weights = []

    interacted_ids = set(
        exclude_ids
    )

    for (
        article_id,
        interaction_type,
    ) in interactions:

        interacted_ids.add(
            article_id
        )

        row_number = (
            article_id_to_row.get(
                article_id
            )
        )

        if row_number is None:
            continue

        weight = (
            INTERACTION_WEIGHTS.get(
                interaction_type,
                1.0,
            )
        )

        text_vectors.append(
            text_matrix[
                row_number
            ].toarray()[0]
        )

        title_vectors.append(
            title_matrix[
                row_number
            ].toarray()[0]
        )

        weights.append(
            weight
        )

    if not text_vectors:
        return []

    text_vectors = np.asarray(
        text_vectors,
        dtype=float,
    )

    title_vectors = np.asarray(
        title_vectors,
        dtype=float,
    )

    weights = np.asarray(
        weights,
        dtype=float,
    ).reshape(
        -1,
        1,
    )

    total_weight = (
        weights.sum()
    )

    if total_weight <= 0:
        return []

    text_profile = (
        text_vectors
        * weights
    ).sum(
        axis=0
    ) / total_weight

    title_profile = (
        title_vectors
        * weights
    ).sum(
        axis=0
    ) / total_weight

    # -----------------------------------------------------------------
    # STEP 6
    # Calculate similarities.
    # -----------------------------------------------------------------

    text_similarities = (
        cosine_similarity(
            text_profile.reshape(
                1,
                -1,
            ),
            text_matrix,
        ).flatten()
    )

    title_similarities = (
        cosine_similarity(
            title_profile.reshape(
                1,
                -1,
            ),
            title_matrix,
        ).flatten()
    )

    # -----------------------------------------------------------------
    # STEP 7
    # Build category preferences using ONLY explicit interactions.
    # -----------------------------------------------------------------

    category_scores = {}

    for (
        article_id,
        interaction_type,
    ) in interactions:

        article = db.session.get(
            Article,
            article_id,
        )

        if article is None:
            continue

        category = (
            safe_text(
                getattr(
                    article,
                    "category",
                    None,
                )
            ).lower()
            or "unknown"
        )

        weight = (
            INTERACTION_WEIGHTS.get(
                interaction_type,
                1.0,
            )
        )

        category_scores[
            category
        ] = (
            category_scores.get(
                category,
                0.0,
            )
            + weight
        )

    category_total = sum(
        category_scores.values()
    )

    if category_total > 0:

        category_preferences = {
            category: score / category_total
            for (
                category,
                score,
            ) in category_scores.items()
        }

    else:

        category_preferences = {}

    category_by_row = (
        build_category_by_row(
            article_index
        )
    )

    # -----------------------------------------------------------------
    # STEP 8
    # Generate candidates.
    # -----------------------------------------------------------------

    candidates = generate_candidates(
        text_similarities=text_similarities,
        title_similarities=title_similarities,
        interacted_ids=interacted_ids,
        article_ids=article_ids,
        article_id_to_row=article_id_to_row,
        candidate_pool_size=max(
            DEFAULT_CANDIDATE_POOL,
            top_n * 5,
        ),
    )

    if not candidates:
        return []

    # -----------------------------------------------------------------
    # STEP 9
    # Calculate personalized scores.
    # -----------------------------------------------------------------

    scored_candidates = (
        calculate_personalized_scores(
            candidates=candidates,
            text_similarities=text_similarities,
            title_similarities=title_similarities,
            category_preferences=category_preferences,
            category_by_row=category_by_row,
            recency_matrix=recency_matrix,
        )
    )

    if not scored_candidates:
        return []

    # -----------------------------------------------------------------
    # STEP 10
    # Diversity re-ranking.
    # -----------------------------------------------------------------

    reranked = diversity_rerank(
        scored_candidates=scored_candidates,
        feature_matrix=feature_matrix,
        category_by_row=category_by_row,
        top_n=top_n,
    )

    return [
        (
            candidate[
                "article_id"
            ],
            float(
                candidate[
                    "score"
                ]
            ),
        )
        for candidate in reranked
    ]


# =====================================================================
# POPULARITY RANKING
# =====================================================================

def popularity_ranking(
    exclude_ids=None,
    top_n=10,
):
    """
    Compatibility/test helper only.

    Return articles ordered by total interaction count.

    IMPORTANT:

        personalized_recommend() NEVER calls this function.

    Production recommendations remain strictly personalized.

    This function exists only because older tests or older code may
    still import it.
    """

    exclude_ids = set(
        exclude_ids or []
    )

    if top_n <= 0:
        return []

    rows = (
        db.session.query(
            Interaction.article_id,
            func.count(
                Interaction.id
            ).label(
                "interaction_count"
            ),
        )
        .group_by(
            Interaction.article_id
        )
        .order_by(
            func.count(
                Interaction.id
            ).desc()
        )
        .all()
    )

    recommendations = []

    for (
        article_id,
        interaction_count,
    ) in rows:

        if article_id in exclude_ids:
            continue

        recommendations.append(
            (
                article_id,
                float(
                    interaction_count
                ),
            )
        )

        if len(
            recommendations
        ) >= top_n:

            break

    return recommendations


# =====================================================================
# COMPATIBILITY FUNCTION
# =====================================================================

def hybrid_recommend(
    user_id,
    top_n=20,
    alpha=1.0,
):
    """
    Compatibility wrapper.

    The old project used the name hybrid_recommend().

    The current production recommender intentionally does not use
    collaborative filtering or NCF.

    Therefore this function simply calls personalized_recommend().

    alpha is retained only for compatibility.
    It has no effect on the result.
    """

    return personalized_recommend(
        user_id=user_id,
        top_n=top_n,
    )


# =====================================================================
# DISPLAY HELPER
# =====================================================================

def print_recommendations(
    recommendations,
):
    """
    Print recommendation results for manual testing.
    """

    if not recommendations:

        print(
            "  No personalized recommendations available."
        )

        print(
            "  The user needs at least one usable interaction."
        )

        return

    for (
        article_id,
        score,
    ) in recommendations:

        article = db.session.get(
            Article,
            article_id,
        )

        if article is None:

            title = "(unknown)"

        else:

            title = article.title

        print(
            f"  [{score:.4f}] "
            f"Article {article_id}: "
            f"{title}"
        )


# =====================================================================
# MANUAL TEST
# =====================================================================

if __name__ == "__main__":

    app = create_app()

    with app.app_context():

        if len(sys.argv) > 1:

            try:

                user_id = int(
                    sys.argv[1]
                )

            except ValueError:

                print(
                    "ERROR: user_id must be an integer."
                )

                sys.exit(1)

        else:

            user_id = 1

        print()

        print(
            "=" * 78
        )

        print(
            "IMPROVED STRICT PER-USER RECOMMENDATION TEST"
        )

        print(
            "=" * 78
        )

        print(
            f"User ID: {user_id}"
        )

        interactions = (
            get_user_interactions(
                user_id
            )
        )

        print(
            f"User interactions: "
            f"{len(interactions)}"
        )

        if interactions:

            print()

            print(
                "User interaction history:"
            )

            for (
                article_id,
                interaction_type,
            ) in interactions:

                print(
                    f"  Article {article_id}: "
                    f"{interaction_type}"
                )

        print()

        print(
            "Top 5 recommendations:"
        )

        recommendations_5 = (
            personalized_recommend(
                user_id=user_id,
                top_n=5,
            )
        )

        print_recommendations(
            recommendations_5
        )

        print()

        print(
            "Top 10 recommendations:"
        )

        recommendations_10 = (
            personalized_recommend(
                user_id=user_id,
                top_n=10,
            )
        )

        print_recommendations(
            recommendations_10
        )

        print()

        print(
            "Top 20 recommendations:"
        )

        recommendations_20 = (
            personalized_recommend(
                user_id=user_id,
                top_n=20,
            )
        )

        print_recommendations(
            recommendations_20
        )

        print(
            "=" * 78
        )